// ============================================================
// POKEDEX 1-251 mit deutschen Namen + Typ + Beschreibung
// ============================================================
const POKEDEX = [
  {n:1,de:'Bisasam',type:'Pflanze/Gift',desc:'Pflanzen-Pokemon. Trägt eine Knospe auf dem Rücken die mit ihm wächst.',color:'#7cb342'},
  {n:2,de:'Bisaknosp',type:'Pflanze/Gift',desc:'Bisasams Entwicklung. Die Knospe wird zur grossen Knospe.',color:'#558b2f'},
  {n:3,de:'Bisaflor',type:'Pflanze/Gift',desc:'Bisaknosps Endform. Eine grosse Blume blüht auf seinem Rücken.',color:'#388e3c'},
  {n:4,de:'Glumanda',type:'Feuer',desc:'Feuer-Echse mit brennender Schwanzflamme. Geht die Flamme aus, stirbt es.',color:'#ff7043'},
  {n:5,de:'Glutexo',type:'Feuer',desc:'Glumandas Entwicklung. Wird hitzköpfiger und stärker.',color:'#e64a19'},
  {n:6,de:'Glurak',type:'Feuer/Flug',desc:'Mächtige Drachen-Echse. Spuckt Feuer das Felsen schmilzt.',color:'#e53935'},
  {n:7,de:'Schiggy',type:'Wasser',desc:'Kleine Schildkröte. Spritzt aus dem Maul Wasser auf Gegner.',color:'#4fc3f7'},
  {n:8,de:'Schillok',type:'Wasser',desc:'Schiggys Entwicklung. Schwimmt sehr schnell mit Pelz-Schwanz.',color:'#0288d1'},
  {n:9,de:'Turtok',type:'Wasser',desc:'Schiggys Endform. Zwei Wasser-Kanonen schiessen aus dem Panzer.',color:'#01579b'},
  {n:10,de:'Raupy',type:'Käfer',desc:'Kleine Raupe mit roter Antenne. Schreckt Feinde mit Stinkdrüse ab.',color:'#9ccc65'},
  {n:11,de:'Safcon',type:'Käfer',desc:'Verhärtet sich um sich zu schützen. Wartet auf Verwandlung.',color:'#cddc39'},
  {n:12,de:'Smettbo',type:'Käfer/Flug',desc:'Wunderschöner Schmetterling. Streut Schuppen-Pulver der Feinde lähmt.',color:'#ab47bc'},
  {n:13,de:'Hornliu',type:'Käfer/Gift',desc:'Stachel-Käfer. Rammt Feinde mit dem Stachel auf dem Kopf.',color:'#fb8c00'},
  {n:14,de:'Kokuna',type:'Käfer/Gift',desc:'Kokon-Form. Reift heran für seine Endform.',color:'#fdd835'},
  {n:15,de:'Bibor',type:'Käfer/Gift',desc:'Killer-Wespe. Sehr aggressiv, hat 3 Stachel.',color:'#fb8c00'},
  {n:16,de:'Taubsi',type:'Normal/Flug',desc:'Kleiner Vogel. Häufig in Wäldern zu sehen.',color:'#a1887f'},
  {n:17,de:'Tauboga',type:'Normal/Flug',desc:'Taubsis Entwicklung. Fliegt schnell und sucht Beute.',color:'#8d6e63'},
  {n:18,de:'Tauboss',type:'Normal/Flug',desc:'Mächtiger Greifvogel. Beschützt sein Revier energisch.',color:'#6d4c41'},
  {n:19,de:'Rattfratz',type:'Normal',desc:'Kleine Maus. Sehr schnell, beisst alles an.',color:'#a1887f'},
  {n:20,de:'Rattikarl',type:'Normal',desc:'Rattfratz Entwicklung. Schneidezähne wachsen ständig.',color:'#795548'},
  {n:21,de:'Habitak',type:'Normal/Flug',desc:'Kleiner Spatz. Pickt Insekten und kleine Pokemon.',color:'#8d6e63'},
  {n:22,de:'Ibitak',type:'Normal/Flug',desc:'Habitaks Entwicklung. Sehr aggressiver Vogel.',color:'#6d4c41'},
  {n:23,de:'Rettan',type:'Gift',desc:'Schlange. Wickelt sich um Beute und beisst.',color:'#9c27b0'},
  {n:24,de:'Arbok',type:'Gift',desc:'Rettan Entwicklung. Muster auf Bauch erschreckt Feinde.',color:'#7b1fa2'},
  {n:25,de:'Pikachu',type:'Elektro',desc:'Maus-Pokemon. Speichert Strom in Backentaschen, schlägt Donnerblitze.',color:'#fbc02d'},
  {n:26,de:'Raichu',type:'Elektro',desc:'Pikachus Entwicklung. 100.000 Volt Spannung im Schwanz.',color:'#ff8f00'},
  {n:27,de:'Sandan',type:'Boden',desc:'Wüsten-Pokemon. Rollt sich zur Kugel zusammen.',color:'#d7ccc8'},
  {n:28,de:'Sandamer',type:'Boden',desc:'Sandans Entwicklung. Krallen schneiden Felsen.',color:'#a1887f'},
  {n:29,de:'Nidoran♀',type:'Gift',desc:'Weibliches Mini-Hörnchen. Friedlicher als das Männchen.',color:'#f48fb1'},
  {n:30,de:'Nidorina',type:'Gift',desc:'Nidoran Entwicklung. Beschützt ihre Babies aggressiv.',color:'#ec407a'},
  {n:31,de:'Nidoqueen',type:'Gift/Boden',desc:'Königin-Form. Schwer gepanzert, sehr stark.',color:'#1976d2'},
  {n:32,de:'Nidoran♂',type:'Gift',desc:'Männliches Mini-Hörnchen. Aggressiver als das Weibchen.',color:'#90caf9'},
  {n:33,de:'Nidorino',type:'Gift',desc:'Nidoran Entwicklung. Kämpft mit Hörnern.',color:'#5c6bc0'},
  {n:34,de:'Nidoking',type:'Gift/Boden',desc:'König-Form. Ein Hieb des Schwanzes zerschmettert Funkmasten.',color:'#1565c0'},
  {n:35,de:'Piepi',type:'Fee',desc:'Mond-Pokemon. Sammelt Mondstein-Splitter.',color:'#f8bbd0'},
  {n:36,de:'Pixi',type:'Fee',desc:'Piepis Entwicklung. Versteckt sich vor Menschen.',color:'#fce4ec'},
  {n:37,de:'Vulpix',type:'Feuer',desc:'Sechsschwanz-Fuchs. Schwänze wachsen mit dem Alter.',color:'#ff8a65'},
  {n:38,de:'Vulnona',type:'Feuer',desc:'Vulpix Entwicklung. Neun Schwänze, lebt 1000 Jahre.',color:'#fbc02d'},
  {n:39,de:'Pummeluff',type:'Normal/Fee',desc:'Singt Schlaflieder. Bläht sich bei Wut auf.',color:'#f8bbd0'},
  {n:40,de:'Knuddeluff',type:'Normal/Fee',desc:'Pummeluffs Entwicklung. Pelzig und kuschelig.',color:'#f48fb1'},
  {n:41,de:'Zubat',type:'Gift/Flug',desc:'Fledermaus. Lebt in dunklen Höhlen, hat keine Augen.',color:'#5c6bc0'},
  {n:42,de:'Golbat',type:'Gift/Flug',desc:'Zubat Entwicklung. Saugt Blut mit grossen Reisszähnen.',color:'#3949ab'},
  {n:43,de:'Myrapla',type:'Pflanze/Gift',desc:'Klein wie eine Pflanze. Verströmt giftiges Pollen.',color:'#7986cb'},
  {n:44,de:'Duflor',type:'Pflanze/Gift',desc:'Myrapla Entwicklung. Stinkt zum Himmel.',color:'#e57373'},
  {n:45,de:'Giflor',type:'Pflanze/Gift',desc:'Duflors Endform. Süsslicher Geruch lockt Beute an.',color:'#fbc02d'},
  {n:46,de:'Paras',type:'Käfer/Pflanze',desc:'Insekt mit Pilzen auf dem Rücken. Pilze nehmen ihm Energie.',color:'#ef5350'},
  {n:47,de:'Parasek',type:'Käfer/Pflanze',desc:'Paras Entwicklung. Pilze kontrollieren das Insekt.',color:'#e53935'},
  {n:48,de:'Bluzuk',type:'Käfer/Gift',desc:'Eine Insekten-Larve. Tagsüber gut versteckt.',color:'#9ccc65'},
  {n:49,de:'Omot',type:'Käfer/Gift',desc:'Bluzuk Entwicklung. Schuppen lähmen Feinde.',color:'#7e57c2'},
  {n:50,de:'Digda',type:'Boden',desc:'Maulwurf. Lebt unter der Erde, sehr scheu.',color:'#a1887f'},
  {n:51,de:'Digdri',type:'Boden',desc:'Drei Maulwürfe in einem. Graben gemeinsam Tunnel.',color:'#795548'},
  {n:52,de:'Mauzi',type:'Normal',desc:'Katzen-Pokemon. Sammelt glänzende Münzen.',color:'#ffeb3b'},
  {n:53,de:'Snobilikat',type:'Normal',desc:'Mauzis Entwicklung. Sehr stolz und elegant.',color:'#fff8e1'},
  {n:54,de:'Enton',type:'Wasser',desc:'Hat Kopfschmerzen die psychische Kräfte auslösen.',color:'#fdd835'},
  {n:55,de:'Entoron',type:'Wasser',desc:'Entons Entwicklung. Schwimmer-Profi.',color:'#0277bd'},
  {n:56,de:'Menki',type:'Kampf',desc:'Affen-Pokemon. Wird sofort wütend, immer.',color:'#bcaaa4'},
  {n:57,de:'Rasaff',type:'Kampf',desc:'Menkis Entwicklung. Gefährlich aggressiv.',color:'#8d6e63'},
  {n:58,de:'Fukano',type:'Feuer',desc:'Hund-Pokemon. Sehr loyal zum Trainer.',color:'#ff7043'},
  {n:59,de:'Arkani',type:'Feuer',desc:'Fukanos Entwicklung. Legendärer Wachhund.',color:'#e65100'},
  {n:60,de:'Quapsel',type:'Wasser',desc:'Kaulquappen-Pokemon. Spirale am Bauch.',color:'#0277bd'},
  {n:61,de:'Quaputzi',type:'Wasser',desc:'Quapsel Entwicklung. Spirale wird grösser.',color:'#01579b'},
  {n:62,de:'Quappo',type:'Wasser/Kampf',desc:'Quaputzis Entwicklung. Sehr starker Schwimmer.',color:'#1565c0'},
  {n:63,de:'Abra',type:'Psycho',desc:'Schläft 18 Stunden am Tag. Teleportiert bei Gefahr.',color:'#ffb74d'},
  {n:64,de:'Kadabra',type:'Psycho',desc:'Abras Entwicklung. Hält Löffel in der Hand.',color:'#ffa726'},
  {n:65,de:'Simsala',type:'Psycho',desc:'Kadabras Endform. IQ über 5000.',color:'#fb8c00'},
  {n:66,de:'Machollo',type:'Kampf',desc:'Vier Arme zum Trainieren der Muskeln.',color:'#9e9d24'},
  {n:67,de:'Maschock',type:'Kampf',desc:'Macholls Entwicklung. Sehr starker Wrestler.',color:'#827717'},
  {n:68,de:'Machomei',type:'Kampf',desc:'Macholls Endform. Hebt 1000 Kilo mit einer Hand.',color:'#558b2f'},
  {n:69,de:'Knofensa',type:'Pflanze/Gift',desc:'Pflanzen-Mund. Wartet auf Beute zwischen Blumen.',color:'#cddc39'},
  {n:70,de:'Ultrigaria',type:'Pflanze/Gift',desc:'Knofensa Entwicklung. Lasso-Ranke fängt Beute.',color:'#9ccc65'},
  {n:71,de:'Sarzenia',type:'Pflanze/Gift',desc:'Ultrigarias Endform. Frisst sogar grosse Pokemon.',color:'#558b2f'},
  {n:72,de:'Tentacha',type:'Wasser/Gift',desc:'Quallen-Pokemon. Tentakeln lähmen Beute.',color:'#42a5f5'},
  {n:73,de:'Tentoxa',type:'Wasser/Gift',desc:'Tentacha Entwicklung. 80 Tentakel können sich strecken.',color:'#1e88e5'},
  {n:74,de:'Kleinstein',type:'Gestein/Boden',desc:'Wandelt sich auf Bergpfaden zur Steinkugel.',color:'#a1887f'},
  {n:75,de:'Georok',type:'Gestein/Boden',desc:'Kleinsteins Entwicklung. Kann ohne Arme rollen.',color:'#8d6e63'},
  {n:76,de:'Geowaz',type:'Gestein/Boden',desc:'Georoks Endform. Steinhart wie Diamant.',color:'#6d4c41'},
  {n:77,de:'Ponita',type:'Feuer',desc:'Feuer-Pferdchen. Mähne aus reinem Feuer.',color:'#fff'},
  {n:78,de:'Gallopa',type:'Feuer',desc:'Ponitas Entwicklung. Galoppiert über Wasser.',color:'#fff'},
  {n:79,de:'Flegmon',type:'Wasser/Psycho',desc:'Sehr langsames Pokemon. Vergesslich.',color:'#f48fb1'},
  {n:80,de:'Lahmus',type:'Wasser/Psycho',desc:'Flegmons Entwicklung. Muschel beisst seinen Schwanz.',color:'#ec407a'},
  {n:81,de:'Magnetilo',type:'Elektro/Stahl',desc:'Magnet-Pokemon. Schwebt mit Magnetkraft.',color:'#90a4ae'},
  {n:82,de:'Magneton',type:'Elektro/Stahl',desc:'Magnetilo Entwicklung. Drei Magnete in einem.',color:'#607d8b'},
  {n:83,de:'Porenta',type:'Normal/Flug',desc:'Ente mit Lauch-Stiel. Verteidigt sich damit.',color:'#fff'},
  {n:84,de:'Dodu',type:'Normal/Flug',desc:'Zwei-Kopf-Vogel. Kann nicht fliegen aber schnell rennen.',color:'#bcaaa4'},
  {n:85,de:'Dodri',type:'Normal/Flug',desc:'Dodu Entwicklung. Drei Köpfe denken alle anders.',color:'#8d6e63'},
  {n:86,de:'Jurob',type:'Wasser',desc:'Robben-Pokemon. Liebt eisige Gewässer.',color:'#fff'},
  {n:87,de:'Jugong',type:'Wasser/Eis',desc:'Jurobs Entwicklung. Schnell wie ein Pfeil unter Wasser.',color:'#b3e5fc'},
  {n:88,de:'Sleima',type:'Gift',desc:'Schleim-Klumpen. Sehr giftig, riecht stinkig.',color:'#9c27b0'},
  {n:89,de:'Sleimok',type:'Gift',desc:'Sleima Entwicklung. Frisst alles in seinem Weg.',color:'#7b1fa2'},
  {n:90,de:'Muschas',type:'Wasser',desc:'Muschel-Pokemon. Beisst mit Zunge zu.',color:'#9c27b0'},
  {n:91,de:'Austos',type:'Wasser/Eis',desc:'Muschas Entwicklung. Stachelige Muschel.',color:'#5e35b1'},
  {n:92,de:'Nebulak',type:'Geist/Gift',desc:'Geist-Wolke. Kann durch Wände gehen.',color:'#9c27b0'},
  {n:93,de:'Alpollo',type:'Geist/Gift',desc:'Nebulak Entwicklung. Schwebt um Mitternacht.',color:'#7b1fa2'},
  {n:94,de:'Gengar',type:'Geist/Gift',desc:'Alpollos Endform. Versteckt sich im Schatten.',color:'#7b1fa2'},
  {n:95,de:'Onix',type:'Gestein/Boden',desc:'Riesen-Steinschlange. 8.8 Meter lang.',color:'#9e9e9e'},
  {n:96,de:'Traumato',type:'Psycho',desc:'Liest deine Träume. Frisst Albträume.',color:'#fff59d'},
  {n:97,de:'Hypno',type:'Psycho',desc:'Traumatos Entwicklung. Pendel hypnotisiert.',color:'#fbc02d'},
  {n:98,de:'Krabby',type:'Wasser',desc:'Krebs mit grossen Scheren. Lebt am Strand.',color:'#ef5350'},
  {n:99,de:'Kingler',type:'Wasser',desc:'Krabby Entwicklung. Riesenschere mit 10000 PS.',color:'#e53935'},
  {n:100,de:'Voltobal',type:'Elektro',desc:'Sieht aus wie Pokeball. Explodiert manchmal.',color:'#e53935'},
  {n:101,de:'Lektrobal',type:'Elektro',desc:'Voltobals Entwicklung. Sehr aggressiv.',color:'#fbc02d'},
  {n:102,de:'Owei',type:'Pflanze/Psycho',desc:'Sechs Eier in einem. Sind eigentlich Pflanzen.',color:'#fbc02d'},
  {n:103,de:'Kokowei',type:'Pflanze/Psycho',desc:'Owei Entwicklung. Drei Köpfe einer Palme.',color:'#fbc02d'},
  {n:104,de:'Tragosso',type:'Boden',desc:'Trägt Knochen seiner Mutter. Sehr traurig.',color:'#bcaaa4'},
  {n:105,de:'Knogga',type:'Boden',desc:'Tragossos Entwicklung. Wirft Knochen wie Bumerang.',color:'#a1887f'},
  {n:106,de:'Kicklee',type:'Kampf',desc:'Hat keine Arme. Sehr lange Beine zum Treten.',color:'#a1887f'},
  {n:107,de:'Nockchan',type:'Kampf',desc:'Box-Champion. Schlagfrequenz: 100 pro Sekunde.',color:'#5d4037'},
  {n:108,de:'Schlurp',type:'Normal',desc:'Lange Zunge die alles abschleckt.',color:'#f48fb1'},
  {n:109,de:'Smogon',type:'Gift',desc:'Stinkende Gas-Wolke. Verströmt giftige Dämpfe.',color:'#7b1fa2'},
  {n:110,de:'Smogmog',type:'Gift',desc:'Smogon Entwicklung. Zwei Köpfe doppelter Gestank.',color:'#5e35b1'},
  {n:111,de:'Rihorn',type:'Boden/Gestein',desc:'Steinharter Nashorn. Rennt durch alles.',color:'#9e9e9e'},
  {n:112,de:'Rizeros',type:'Boden/Gestein',desc:'Rihorns Entwicklung. Hirn so klein, dass er nicht denkt.',color:'#757575'},
  {n:113,de:'Chaneira',type:'Normal',desc:'Trägt Glücks-Ei. Sehr gutmütig, heilt Verletzte.',color:'#f8bbd0'},
  {n:114,de:'Tangela',type:'Pflanze',desc:'Voller blauer Lianen. Niemand sieht sein Gesicht.',color:'#1976d2'},
  {n:115,de:'Kangama',type:'Normal',desc:'Trägt Baby im Beutel. Beschützt es bis zum Tod.',color:'#a1887f'},
  {n:116,de:'Seeper',type:'Wasser',desc:'See-Pferdchen. Wirft Tinte zum Schutz.',color:'#0277bd'},
  {n:117,de:'Seemon',type:'Wasser',desc:'Seepers Entwicklung. Sehr schneller Schwimmer.',color:'#01579b'},
  {n:118,de:'Goldini',type:'Wasser',desc:'Goldfisch-Pokemon. Stachel auf der Stirn.',color:'#fff'},
  {n:119,de:'Golking',type:'Wasser',desc:'Goldini Entwicklung. König der Flüsse.',color:'#fff'},
  {n:120,de:'Sterndu',type:'Wasser',desc:'Stern aus dem Meer. Roter Kern leuchtet.',color:'#ffeb3b'},
  {n:121,de:'Starmie',type:'Wasser/Psycho',desc:'Sterndu Entwicklung. Sendet Funksignale ins All.',color:'#7b1fa2'},
  {n:122,de:'Pantimos',type:'Psycho/Fee',desc:'Pantomime. Erschafft unsichtbare Wände mit Händen.',color:'#f48fb1'},
  {n:123,de:'Sichlor',type:'Käfer/Flug',desc:'Sichel-Klingen statt Hände. Sehr schneller Krieger.',color:'#43a047'},
  {n:124,de:'Rossana',type:'Eis/Psycho',desc:'Schöne Eis-Sängerin. Singt traurige Lieder.',color:'#9c27b0'},
  {n:125,de:'Elektek',type:'Elektro',desc:'Trinkt Strom wie Wasser. Frisst Stromzähler.',color:'#fbc02d'},
  {n:126,de:'Magmar',type:'Feuer',desc:'Lebt in Vulkanen. Spuckt geschmolzenes Gestein.',color:'#e53935'},
  {n:127,de:'Pinsir',type:'Käfer',desc:'Riesenscheren auf Kopf. Hebt 1000-faches Gewicht.',color:'#a1887f'},
  {n:128,de:'Tauros',type:'Normal',desc:'Drei Schwänze. Wütender Stier, peitscht sich selbst.',color:'#a1887f'},
  {n:129,de:'Karpador',type:'Wasser',desc:'Schwächstes Pokemon. Springt nur aus dem Wasser.',color:'#ff7043'},
  {n:130,de:'Garados',type:'Wasser/Flug',desc:'Karpadors Entwicklung! Drachen-Form, sehr aggressiv.',color:'#1565c0'},
  {n:131,de:'Lapras',type:'Wasser/Eis',desc:'Sanftes Riesen-Pokemon. Singt schön, trägt Menschen.',color:'#4fc3f7'},
  {n:132,de:'Ditto',type:'Normal',desc:'Verwandelt sich in alles. Kopiert sogar DNA.',color:'#f8bbd0'},
  {n:133,de:'Evoli',type:'Normal',desc:'Hat 8 verschiedene Entwicklungs-Formen. Sehr anpassungsfähig.',color:'#a1887f'},
  {n:134,de:'Aquana',type:'Wasser',desc:'Evoli mit Wasserstein. Verschmilzt mit Wasser.',color:'#0288d1'},
  {n:135,de:'Blitza',type:'Elektro',desc:'Evoli mit Donnerstein. Reizbares Fell knistert.',color:'#ffeb3b'},
  {n:136,de:'Flamara',type:'Feuer',desc:'Evoli mit Feuerstein. Innere Glut: 900 Grad.',color:'#e53935'},
  {n:137,de:'Porygon',type:'Normal',desc:'Erstes Computer-Pokemon. Lebt in Internet.',color:'#f48fb1'},
  {n:138,de:'Amonitas',type:'Gestein/Wasser',desc:'Vor 300 Mio Jahren. Aus Bernstein wiederbelebt.',color:'#90a4ae'},
  {n:139,de:'Amoroso',type:'Gestein/Wasser',desc:'Amonitas Entwicklung. 10 Tentakel.',color:'#607d8b'},
  {n:140,de:'Kabuto',type:'Gestein/Wasser',desc:'Pfeilschwanz-Krebs. Roter Augenpunkt.',color:'#a1887f'},
  {n:141,de:'Kabutops',type:'Gestein/Wasser',desc:'Kabuto Entwicklung. Schwimmer-Krieger.',color:'#5d4037'},
  {n:142,de:'Aerodactyl',type:'Gestein/Flug',desc:'Urzeit-Drache. Aus Bernstein wiederbelebt.',color:'#7e57c2'},
  {n:143,de:'Relaxo',type:'Normal',desc:'Schläft 20 Stunden täglich. Frisst 400 Kilo am Tag.',color:'#5d4037'},
  {n:144,de:'Arktos',type:'Eis/Flug',desc:'Legendärer Eis-Vogel. Bringt Schnee wo er fliegt.',color:'#4fc3f7'},
  {n:145,de:'Zapdos',type:'Elektro/Flug',desc:'Legendärer Donner-Vogel. Schiesst Blitze aus Federn.',color:'#fdd835'},
  {n:146,de:'Lavados',type:'Feuer/Flug',desc:'Legendärer Feuer-Vogel. Hinterlässt Feuer-Spur.',color:'#ff5722'},
  {n:147,de:'Dratini',type:'Drache',desc:'Drachen-Baby. Wechselt seine Haut beim Wachsen.',color:'#90caf9'},
  {n:148,de:'Dragonir',type:'Drache',desc:'Dratini Entwicklung. Glücksbringer in Asien.',color:'#42a5f5'},
  {n:149,de:'Dragoran',type:'Drache/Flug',desc:'Dratinis Endform. Fliegt ums die Welt in 16 Stunden.',color:'#f57f17'},
  {n:150,de:'Mewtu',type:'Psycho',desc:'Künstlich aus Mews DNA erschaffen. Stärkstes Pokemon.',color:'#9c27b0'},
  {n:151,de:'Mew',type:'Psycho',desc:'Hat DNA aller Pokemon. Sehr selten gesehen.',color:'#f48fb1'},
  // Gen 2 (Auswahl)
  {n:152,de:'Endivie',type:'Pflanze',desc:'Pflanzen-Starter Gen 2. Hat ein Blatt am Kopf.',color:'#a5d6a7'},
  {n:153,de:'Lorblatt',type:'Pflanze',desc:'Endivies Entwicklung.',color:'#81c784'},
  {n:154,de:'Meganie',type:'Pflanze',desc:'Endivies Endform. Heilt mit Blumen-Duft.',color:'#43a047'},
  {n:155,de:'Feurigel',type:'Feuer',desc:'Feuer-Igel. Stacheln werden bei Wut zu Flammen.',color:'#bf360c'},
  {n:156,de:'Igelavar',type:'Feuer',desc:'Feurigels Entwicklung.',color:'#d84315'},
  {n:157,de:'Tornupto',type:'Feuer',desc:'Feurigels Endform. Lava-Glut umhüllt seinen Körper.',color:'#bf360c'},
  {n:158,de:'Karnimani',type:'Wasser',desc:'Krokodil-Baby. Beisst alles, was sich bewegt.',color:'#1976d2'},
  {n:159,de:'Tyracroc',type:'Wasser',desc:'Karnimanis Entwicklung.',color:'#1565c0'},
  {n:160,de:'Impergator',type:'Wasser',desc:'Karnimanis Endform. Riesen-Maul, ein Schnapp und du bist weg.',color:'#0d47a1'},
  {n:161,de:'Wiesor',type:'Normal',desc:'Wiesel-Pokemon. Jagt 24/7 Beute.',color:'#fff3e0'},
  {n:162,de:'Wiesenior',type:'Normal',desc:'Wiesors Entwicklung.',color:'#ffe082'},
  {n:163,de:'Hoothoot',type:'Normal/Flug',desc:'Eulen-Pokemon. Steht auf einem Bein.',color:'#a1887f'},
  {n:164,de:'Noctuh',type:'Normal/Flug',desc:'Hoothoots Entwicklung. Sieht im Dunkeln gut.',color:'#8d6e63'},
  {n:165,de:'Ledyba',type:'Käfer/Flug',desc:'Marienkäfer mit 5 Punkten. Sehr scheu.',color:'#e53935'},
  {n:166,de:'Ledian',type:'Käfer/Flug',desc:'Ledybas Entwicklung. Stern-Marienkäfer.',color:'#fdd835'},
  {n:167,de:'Webarak',type:'Käfer/Gift',desc:'Spinnen-Pokemon. Spinnt klebrige Netze.',color:'#fdd835'},
  {n:168,de:'Ariados',type:'Käfer/Gift',desc:'Webaraks Entwicklung. Lange Beine, schnell.',color:'#d32f2f'},
  {n:169,de:'Iksbat',type:'Gift/Flug',desc:'Golbats Entwicklung. Saugt nur ausgewählten Opfern Blut.',color:'#7b1fa2'},
  {n:170,de:'Lampi',type:'Wasser/Elektro',desc:'Glüh-Fisch. Lampe an der Antenne.',color:'#1976d2'},
  {n:171,de:'Lanturn',type:'Wasser/Elektro',desc:'Lampi Entwicklung. Leuchtet die ganze Tiefsee.',color:'#01579b'},
  {n:172,de:'Pichu',type:'Elektro',desc:'Pikachus Vorform. Baby-Maus. Funkt unbeabsichtigt.',color:'#fff59d'},
  {n:173,de:'Pii',type:'Fee',desc:'Piepis Vorform. Knuddelig.',color:'#f8bbd0'},
  {n:174,de:'Fluffeluff',type:'Normal/Fee',desc:'Pummeluffs Vorform. Bei Wut Tropfen-Augen.',color:'#fce4ec'},
  {n:175,de:'Togepi',type:'Fee',desc:'Schlüpft aus glücklichem Ei. Bringt Glück.',color:'#fff9c4'},
  {n:176,de:'Togetic',type:'Fee/Flug',desc:'Togepis Entwicklung. Schwebt auf Glücks-Wolken.',color:'#f8bbd0'},
  {n:177,de:'Natu',type:'Psycho/Flug',desc:'Hüpft viel. Lebt auf Bäumen.',color:'#558b2f'},
  {n:178,de:'Xatu',type:'Psycho/Flug',desc:'Natus Entwicklung. Steht den ganzen Tag still.',color:'#43a047'},
  {n:179,de:'Voltilamm',type:'Elektro',desc:'Lammigi! Elektrizität in der Wolle.',color:'#fce4ec'},
  {n:180,de:'Waaty',type:'Elektro',desc:'Voltilamms Entwicklung. Antenne empfängt Strom.',color:'#f48fb1'},
  {n:181,de:'Ampharos',type:'Elektro',desc:'Waatys Endform. Schwanz leuchtet so hell, sieht man im All.',color:'#fbc02d'},
  {n:182,de:'Blubella',type:'Pflanze',desc:'Mit Sonnenstein aus Duflor. Tanzt schön.',color:'#fbc02d'},
  {n:183,de:'Marill',type:'Wasser/Fee',desc:'Wasser-Maus. Schwanz mit Boje am Ende.',color:'#42a5f5'},
  {n:184,de:'Azumarill',type:'Wasser/Fee',desc:'Marills Entwicklung. Hört durchs Wasser.',color:'#1976d2'},
  {n:185,de:'Mogelbaum',type:'Gestein',desc:'Tarnt sich als Baum. Mag kein Wasser.',color:'#5d4037'},
  {n:186,de:'Quaxo',type:'Wasser',desc:'Quappos Entwicklung mit König-Stein.',color:'#0277bd'},
  {n:187,de:'Hoppspross',type:'Pflanze/Flug',desc:'Schwebt im Wind. Tanzt um Honig zu locken.',color:'#9ccc65'},
  {n:188,de:'Hubelupf',type:'Pflanze/Flug',desc:'Hoppspross Entwicklung.',color:'#7cb342'},
  {n:189,de:'Papungha',type:'Pflanze/Flug',desc:'Hoppspross Endform. Pusteblume.',color:'#fff'},
  {n:190,de:'Griffel',type:'Normal',desc:'Affen-Pokemon. Schwanz greift wie eine Hand.',color:'#fbc02d'},
  {n:191,de:'Sonnkern',type:'Pflanze',desc:'Pflanzen-Saat. Sonnenanbeter.',color:'#fbc02d'},
  {n:192,de:'Sonnflora',type:'Pflanze',desc:'Sonnkerns Entwicklung. Sonnenblume.',color:'#ffeb3b'},
  {n:193,de:'Yanma',type:'Käfer/Flug',desc:'Libellen-Pokemon. Sieht 360 Grad.',color:'#e53935'},
  {n:194,de:'Felino',type:'Wasser/Boden',desc:'Schleim-Lurch. Lebt in Schlamm.',color:'#1976d2'},
  {n:195,de:'Morlord',type:'Wasser/Boden',desc:'Felinos Entwicklung.',color:'#1565c0'},
  {n:196,de:'Psiana',type:'Psycho',desc:'Evoli am Tag entwickelt. Sehr loyal.',color:'#ce93d8'},
  {n:197,de:'Nachtara',type:'Unlicht',desc:'Evoli nachts entwickelt. Glüht im Dunkeln.',color:'#212121'},
  {n:198,de:'Kramurx',type:'Unlicht/Flug',desc:'Schwarzer Vogel. Bringt Unglück.',color:'#212121'},
  {n:199,de:'Laschoking',type:'Wasser/Psycho',desc:'Flegmons andere Entwicklung. König mit Krone.',color:'#f48fb1'},
  {n:200,de:'Traunfugil',type:'Geist',desc:'Geist mit Stachel-Haaren. Singt traurig.',color:'#9e9d24'},
  {n:201,de:'Icognito',type:'Psycho',desc:'Buchstaben-Pokemon. 28 verschiedene Formen.',color:'#212121'},
  {n:202,de:'Woingenau',type:'Psycho',desc:'Holt einmal aus, dann gibts ein Riesen-Hau.',color:'#1976d2'},
  {n:203,de:'Girafarig',type:'Normal/Psycho',desc:'Giraffe mit zweitem Mini-Kopf am Schwanz.',color:'#ffeb3b'},
  {n:204,de:'Tannza',type:'Käfer',desc:'Pinien-Zapfen-Käfer. Bewegt sich nicht.',color:'#5d4037'},
  {n:205,de:'Forstellka',type:'Käfer/Stahl',desc:'Tannzas Entwicklung. Stahl-Schale.',color:'#37474f'},
  {n:206,de:'Dummisel',type:'Normal',desc:'Hörte oft was - jetzt taub. Sehr schnell.',color:'#fff8e1'},
  {n:207,de:'Skorgla',type:'Boden/Flug',desc:'Skorpion mit Flügeln. Stachel injiziert Gift.',color:'#7b1fa2'},
  {n:208,de:'Stahlos',type:'Stahl/Boden',desc:'Onix mit Metall-Stein. Härter als Diamant.',color:'#90a4ae'},
  {n:209,de:'Snubbull',type:'Fee',desc:'Bulldoggen-Welpe. Frech aber lieb.',color:'#f8bbd0'},
  {n:210,de:'Granbull',type:'Fee',desc:'Snubbulls Entwicklung. Reisszähne.',color:'#5e35b1'},
  {n:211,de:'Baldorfish',type:'Wasser/Gift',desc:'Kugelfisch. Bläht sich auf bei Gefahr.',color:'#fbc02d'},
  {n:212,de:'Scherox',type:'Käfer/Stahl',desc:'Sichlor mit Metall-Stein. Schere wie Stahl.',color:'#d32f2f'},
  {n:213,de:'Pottrott',type:'Käfer/Gestein',desc:'Pillen-Pokemon. Steht jahrelang still.',color:'#5d4037'},
  {n:214,de:'Skaraborn',type:'Käfer/Kampf',desc:'Riesenkäfer mit Horn. Sehr stark.',color:'#1565c0'},
  {n:215,de:'Sniebel',type:'Unlicht/Eis',desc:'Eis-Wiesel. Sehr listig und gemein.',color:'#37474f'},
  {n:216,de:'Teddiursa',type:'Normal',desc:'Bär-Baby. Liebt Honig über alles.',color:'#fbc02d'},
  {n:217,de:'Ursaring',type:'Normal',desc:'Teddiursas Entwicklung. Mächtiger Bär.',color:'#5d4037'},
  {n:218,de:'Schneckmag',type:'Feuer',desc:'Lava-Schnecke. Hinterlässt Lava-Spur.',color:'#d32f2f'},
  {n:219,de:'Magcargo',type:'Feuer/Gestein',desc:'Schneckmag Entwicklung. Lava-Schnecke mit Krater.',color:'#bf360c'},
  {n:220,de:'Quiekel',type:'Eis/Boden',desc:'Mini-Mammut. Stoßzähne wachsen ständig.',color:'#a1887f'},
  {n:221,de:'Keifel',type:'Eis/Boden',desc:'Quiekels Entwicklung. Schwere Stoßzähne.',color:'#5d4037'},
  {n:222,de:'Corasonn',type:'Wasser/Gestein',desc:'Korallen-Pokemon. Lebt im warmen Meer.',color:'#f48fb1'},
  {n:223,de:'Remoraid',type:'Wasser',desc:'Schiess-Fisch. Trifft präzise auf 100m.',color:'#90a4ae'},
  {n:224,de:'Octillery',type:'Wasser',desc:'Remoraid Entwicklung. Tintenfisch-Kanone.',color:'#d32f2f'},
  {n:225,de:'Botogel',type:'Eis/Flug',desc:'Liefer-Vogel. Trägt Geschenke im Beutel.',color:'#e53935'},
  {n:226,de:'Mantax',type:'Wasser/Flug',desc:'Manta-Rochen. Springt aus dem Meer.',color:'#1565c0'},
  {n:227,de:'Panzaeron',type:'Stahl/Flug',desc:'Stahl-Vogel. Federn aus Metall.',color:'#37474f'},
  {n:228,de:'Hunduster',type:'Unlicht/Feuer',desc:'Hund mit Hörnern. Bellt wie aus der Hölle.',color:'#212121'},
  {n:229,de:'Hundemon',type:'Unlicht/Feuer',desc:'Hundusters Entwicklung. Sehr gefährlich.',color:'#212121'},
  {n:230,de:'Seedraking',type:'Wasser/Drache',desc:'Seemons Entwicklung. König der Tiefsee.',color:'#0d47a1'},
  {n:231,de:'Phanpy',type:'Boden',desc:'Mini-Elefant. Sehr lieb und neugierig.',color:'#1976d2'},
  {n:232,de:'Donphan',type:'Boden',desc:'Phanpy Entwicklung. Rollt wie Reifen.',color:'#90a4ae'},
  {n:233,de:'Porygon2',type:'Normal',desc:'Porygons Entwicklung. KI lernt selbst.',color:'#1976d2'},
  {n:234,de:'Damhirplex',type:'Normal',desc:'Hirsch mit Geweih. Schnell und stolz.',color:'#5d4037'},
  {n:235,de:'Farbeagle',type:'Normal',desc:'Maler-Hund. Schwanz ist ein Pinsel.',color:'#fff'},
  {n:236,de:'Rabauz',type:'Kampf',desc:'Kampfsport-Baby. Übt Tag und Nacht.',color:'#42a5f5'},
  {n:237,de:'Kapoera',type:'Kampf',desc:'Rabauz Entwicklung. Tanzt wie Capoeira.',color:'#9c27b0'},
  {n:238,de:'Kussilla',type:'Eis/Psycho',desc:'Kuss-Baby mit Eis-Atem.',color:'#fce4ec'},
  {n:239,de:'Elekid',type:'Elektro',desc:'Elektek-Baby. Zwei Hörner-Antennen.',color:'#fbc02d'},
  {n:240,de:'Magby',type:'Feuer',desc:'Magmar-Baby. Atmet kleine Feuerbälle.',color:'#e53935'},
  {n:241,de:'Miltank',type:'Normal',desc:'Milch-Kuh. Eine Schluck Milch heilt alles.',color:'#f48fb1'},
  {n:242,de:'Heiteira',type:'Normal',desc:'Chaneiras Entwicklung. Bringt Glück.',color:'#fce4ec'},
  {n:243,de:'Raikou',type:'Elektro',desc:'Legendärer Donner-Tiger. Donnerwolken folgen ihm.',color:'#fbc02d'},
  {n:244,de:'Entei',type:'Feuer',desc:'Legendärer Lava-Hund. Vulkane brechen aus wo er rennt.',color:'#bf360c'},
  {n:245,de:'Suicune',type:'Wasser',desc:'Legendärer Aurora-Wolf. Reinigt verschmutztes Wasser.',color:'#1976d2'},
  {n:246,de:'Larvitar',type:'Gestein/Boden',desc:'Frisst sich durch Berge.',color:'#558b2f'},
  {n:247,de:'Pupitar',type:'Gestein/Boden',desc:'Larvitars Entwicklung. Hartes Gehäuse.',color:'#558b2f'},
  {n:248,de:'Despotar',type:'Gestein/Unlicht',desc:'Larvitar-Endform. Erschüttert Berge.',color:'#558b2f'},
  {n:249,de:'Lugia',type:'Psycho/Flug',desc:'Hüter der Meere. Ein Flügelschlag - 40 Tage Sturm.',color:'#90caf9'},
  {n:250,de:'Ho-Oh',type:'Feuer/Flug',desc:'Phönix-Pokemon. Regenbogen folgt seinen Federn.',color:'#ff9800'},
  {n:251,de:'Celebi',type:'Psycho/Pflanze',desc:'Reist durch die Zeit. Wenn es erscheint, bringt es Wunder.',color:'#43a047'}
];
